services:
  db:
    image: postgres
    container_name: postgres_production
    restart: always
    env_file: 
      - .env.production
    ports:
      - "5434:5432"
    volumes:
      - pgdata_production:/var/lib/postgresql/data

volumes:
  pgdata_production: